
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

// GET all reports for a specific User (Patient or Doctor)
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const userId = searchParams.get('userId'); 

  if (!userId) return NextResponse.json({ error: 'Missing userId' }, { status: 400 });

  try {
    const reports = await prisma.medicalReport.findMany({
      where: {
        OR: [
          { individualId: userId },
          { doctorId: userId } // A doctor can also see reports they generated
        ]
      },
      include: {
        individual: { select: { firstName: true, lastName: true } },
        doctor: { select: { firstName: true, lastName: true } }
      },
      orderBy: { createdAt: 'desc' }
    });

    return NextResponse.json(reports);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// CREATE a new Medical Report (Usually from AI Voice Analysis result)
export async function POST(request: Request) {
  try {
    const { individualId, doctorId, title, aiAnalysis, transcript, audioUrl } = await request.json();

    const report = await prisma.medicalReport.create({
      data: {
        individualId,
        doctorId: doctorId || undefined, // Optional if generated by patient self-scan
        title,
        aiAnalysis,
        transcript,
        audioUrl
      }
    });

    return NextResponse.json(report);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
